dist: xenial
language: python
cache: pip
python:
  - "3.6"
env:
  - REQ=""
matrix:
  include:
    - python: "3.4"
      env: REQ="Django>=1.11"
    - python: "3.4"
      env: REQ="Django>=2.0"
    - python: "3.5"
      env: REQ="Django>=1.11"
    - python: "3.5"
      env: REQ="Django>=2.0"
    - python: "3.5"
      env: REQ="Django>=2.1"
    - python: "3.5"
      env: REQ="Django>=2.2"
    - python: "3.6"
      env: REQ="Django>=1.11"
    - python: "3.6"
      env: REQ="Django>=2.0"
    - python: "3.6"
      env: REQ="Django>=2.1"
    - python: "3.6"
      env: REQ="Django>=2.2"
install:
  - pip install -U pip wheel setuptools
  - pip install $REQ
  - python setup.py install
script: "cd tests && ./manage.py test --exclude-tag=ssh testapp"
